### ISSUE TITLE
请问放在哪个位置

### ISSUE THREAD

**Issue by 3wadasqw** [OSSSY152/AzurLanePaintingLocalization#2]

**Comment by 3wadasqw** [comment]
求大佬告知

**Comment by OSSSY152** [comment]
增加了教程，希望可以帮到你:-)

**Comment by 3wadasqw** [comment]
多谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 晚上9:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OSSSY152/AzurLanePaintingLocalization] 请问放在哪个位置 (#2)





 
增加了教程，希望可以帮到你:-)

**Comment by 3wadasqw** [comment]
一直卡在这个开始导入文件半小时了，请问怎么办...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OSSSY152/AzurLanePaintingLocalization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OSSSY152/AzurLanePaintingLocalization] 请问放在哪个位置 (#2)





 
增加了教程，希望可以帮到你:-)

**Comment by OSSSY152** [comment]
卡在哪里，是本地化的更新还是立绘的导出？
如果是立绘导出的话，有按照[ALPT的教程](https://www.bigfun.cn/post/219941)一步步来吗？把**Texture2D文件**和**对应的mesh文件**都拖进左侧列表里，再点“导出”就可以了。如果只拖进了mesh的话，在拖进Texture2D之前进度条会一直保持在一半的

btw，如果1.5.2版程序无法关闭的话用任务管理器强行关闭

**Comment by 3wadasqw** [comment]
卡在了，把文件拖入alpt的时候，就底下进度条一直没动，底下一直写开始导入文件..

**Comment by OSSSY152** [comment]
抱歉这几天很忙。。问题解决了吗？如果在github不方便说的话可以加一下软件/教程作者的QQ群，群号看他的B站动态
