### ISSUE TITLE
关于部分分离立绘的问题

### ISSUE THREAD

**Issue by kyangconn** [OSSSY152/AzurLanePaintingLocalization#9]
我在尝试更新的时候发现阿达尔伯特亲王的立绘存在多个不完整立绘，且其他的也存在相同现象，我不知道该怎么搞这个。希望能给个办法。

**Comment by OSSSY152** [comment]
你是指后缀[n]这种的吗，黄鸡这两年好多新立绘都改成像这样的分离式了，并且这边暂时没找到 ~~(也懒得找了)~~ 可用于拼装完整立绘的拆包数据

所以...PS大法好XD

**Comment by kyangconn** [comment]
不是。。例子是阿达尔伯特亲王皮肤，那个解出来会有组合的图，人物和舰装。
![adaerbote_jz](https://user-images.githubusercontent.com/104826731/210539664-110637ab-adc7-4063-8119-77ec5f32d94d.png)
![adaerbote_rw](https://user-images.githubusercontent.com/104826731/210539681-3d403258-1270-4072-82d4-15d9d94e69c5.png)
![adaerbote](https://user-images.githubusercontent.com/104826731/210539685-ec2d5319-a1e6-4715-ae47-26ad3673bf53.png)
这种图似乎没有办法合成一个完整的立绘。后缀_n好像是代表无背景来着，总之合成也会重复（试图发动大佬来解决合成立绘问题）。
不过我还发现另外一个有做合成立绘的，项目叫AzurLanePaintingAnalysis-Kt。（

**Comment by kyangconn** [comment]
对了，差点忘记了，就是制作文件时应该根据什么来做，分离出的Texture2D的有_rw, _jz的来还是按照painting文件夹里的_2_n来做，因为不清楚直接按照painting文件夹来是否能被程序识别？

**Comment by kyangconn** [comment]
抱歉！我没有看到作者你的更新！我现在看到了，我理解了！但是我还是要做一个我的本地化文件（
